version: "3.7"

services:
  flask_app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile-devserver
    environment:
      - PORT_APP=3000
      - PORT_API=4000
      - THREADS=without
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - slow_api

  flask_app_threaded:
    build:
      context: ./flask_app
      dockerfile: Dockerfile-devserver
    environment:
      - PORT_APP=3001
      - PORT_API=4000
      - THREADS=with
    ports:
      - "127.0.0.1:3001:3001"
    depends_on:
      - slow_api

  slow_api:
    build: ./slow_api
    environment:
      - PORT=4000
    expose:
      - "4000"